# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 772a631baf95d90b91bbced1278376e7071856f935592ca5cb3c7208c5e35cf6038df59dbd1db187b47a008a840bf58717cc8534010b724633cb91bc2e667a30

test:
  secret_key_base: 11eebea13429f0fde64157580e7c2f3305579d7ef2799f966bd46f4907508d74905c416f5b12767398b69409d4d610b9e4b30e56d6257ed7831d68e481033832

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
